version: '2'
services:
  # 参考 https://gist.github.com/boiyaa/ad7405cd17d090a52b57728d9b0985cb
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:10.6.4-ce.0
    volumes:
      - etc:/etc/gitlab
      - log:/var/log/gitlab
      - opt:/var/opt/gitlab
    ports:
      - "10080:10080"
      - "10443:443"
      - "10022:22"
    restart: always
    hostname: 'example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://example.com:10080'
        # 参考https://docs.gitlab.com/ce/pages/administration.html
        pages_external_url 'http://example.com:10080'
        gitlab_rails['gravatar_enabled'] = false
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['gitlab_ssh_host'] = 'example.com:10022'
        gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
        # バックアップデータの保存期間(秒)を一週間に設定
        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.example.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = "smtp.example.com"
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close thise this block with 'EOS' below
          main: # 'main' is the GitLab 'provider ID' of this LDAP server
            label: 'LDAP'
            host: 'example.com'
            port: 389
            uid: 'sAMAccountName'
            method: 'plain'
            bind_dn: 'user@example.com'
            password: 'password'
            active_directory: true
            allow_username_or_email_login: false
            base: 'dc=example,dc=com'
            attributes:
              username: 'sAMAccountName'
              email:    'mail'
              name:       'cn'
              first_name: 'givenName'
              last_name:  'sn'
        EOS
    networks:
      - common
networks:
  common:
    external: true
volumes:
  etc:
  log:
  opt:
