version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins:2.60.3
    ports:
      - "8090:8080"
    restart: always
    volumes:
      - data:/var/jenkins_home
    networks:
      - common
networks:
  common:
    external: true
volumes:
  data:
