version: '3'
services:
  growi:
    image: weseek/growi:latest
    container_name: growi
    restart: always
    ports:
      - 3100:3000    # localhost only by default
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - http_proxy=http://example.com:8080
      - https_proxy=http://example.com:8080
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=changeme
      # - FILE_UPLOAD=local    # activate this line if you use local storage of server rather than AWS
      # - MATHJAX=1            # activate this line if you want to use MathJax
      # - PLANTUML_URI=http:// # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
    #command: "dockerize
    #          -wait tcp://mongo:27017
    #          -wait tcp://elasticsearch:9200
    #          -timeout 60s
    #          npm run server:prod"
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:3.4
    container_name: growi_mongo
    volumes:
      - growi_mongo_configdb:/data/configdb
      - growi_mongo_db:/data/db

  elasticsearch:
    image: elasticsearch:5.3-alpine
    container_name: growi_elasticsearch
    environment:
      - http_proxy=http://example.com:8080
      - https_proxy=http://example.com:8080
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji;
        ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;
        /docker-entrypoint.sh elasticsearch"
    volumes:
      - growi_es_data:/usr/share/elasticsearch/data
      - growi_es_plugins:/usr/share/elasticsearch/plugins
      - growi_es_config:/usr/share/elasticsearch/config

volumes:
  growi_data:
  growi_mongo_configdb:
  growi_mongo_db:
  growi_es_data:
  growi_es_plugins:
  growi_es_config:
