# LDAP 認証は /opt/bitnami/testlink/config.inc.php で設定する
version: '2'
services:
  mariadb:
    image: bitnami/mariadb
    container_name: testlink-mariadb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - C:\Docker\testlink\mariadb_data:/bitnami
  testlink:
    image: bitnami/testlink
    container_name: testlink
    restart: always
    ports:
      - '3080:80'
      - '443:443'
    volumes:
      - C:\Docker\testlink\testlink_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin
      - TESTLINK_EMAIL=testlink@example.com
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=25
