version: '3.1'
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - common

  chronograf:
    container_name: chronograf
    image: chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
    volumes:
      - chronograf:/var/lib/chronograf
    networks:
      - common

  grafana:
    container_name: grafana
    image: grafana/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - common

networks:
  common:
    external: true
volumes:
  influxdb:
  chronograf:
  grafana:
